(cl:defpackage my_odometry-srv
  (:use )
  (:export
   "EMPTYREQUEST"
   "<EMPTYREQUEST-REQUEST>"
   "EMPTYREQUEST-REQUEST"
   "<EMPTYREQUEST-RESPONSE>"
   "EMPTYREQUEST-RESPONSE"
   "STATUSMSG"
   "<STATUSMSG-REQUEST>"
   "STATUSMSG-REQUEST"
   "<STATUSMSG-RESPONSE>"
   "STATUSMSG-RESPONSE"
   "ODOM_UPDATE_SRV"
   "<ODOM_UPDATE_SRV-REQUEST>"
   "ODOM_UPDATE_SRV-REQUEST"
   "<ODOM_UPDATE_SRV-RESPONSE>"
   "ODOM_UPDATE_SRV-RESPONSE"
  ))

